// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Teacher_signup', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Teacher_signup', async function() {
    await driver.get("http://localhost:3000/teacher/signup")
    await driver.manage().window().setRect({ width: 1382, height: 754 })
    await driver.findElement(By.css(".input_box:nth-child(1) > input")).click()
    await driver.findElement(By.css(".input_box:nth-child(1) > input")).sendKeys("John Smith")
    await driver.findElement(By.css(".input_box:nth-child(2) > input")).click()
    await driver.findElement(By.css(".input_box:nth-child(2) > input")).sendKeys("johnsmith")
    await driver.findElement(By.css(".input_box:nth-child(3) > input")).click()
    await driver.findElement(By.css(".input_box:nth-child(3) > input")).sendKeys("john.smith@example.com")
    await driver.findElement(By.css(".input_box > .flex > input")).click()
    await driver.findElement(By.css(".input_box > .flex > input")).sendKeys("Johnsmith@1234")
    await driver.findElement(By.name("university")).click()
    {
      const dropdown = await driver.findElement(By.name("university"))
      await dropdown.findElement(By.xpath("//option[. = 'New Horizon']")).click()
    }
    await driver.findElement(By.css(".input_box:nth-child(6) > .w-full")).click()
    await driver.wait(until.elementLocated(By.id("645bed1d81ae8cd7a2826a09")), 80000)
    {
      const dropdown = await driver.findElement(By.css(".input_box:nth-child(6) > .w-full"))
      await dropdown.findElement(By.xpath("//option[. = 'Department of Information Technology']")).click()
    }
    await driver.findElement(By.css(".sign_up_btn")).click()
    // await driver.findElement(By.css(".text-4xl")).click()
    // assert(await driver.findElement(By.css(".text-4xl")).getText() == "PENDING")
  })
})
