// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('University__login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('University__login', async function() {
    await driver.get("http://localhost:3000/university/login")
    await driver.manage().window().setRect({ width: 1382, height: 754 })
    await driver.findElement(By.css(".input_box > input")).click()
    await driver.findElement(By.css(".input_box > input")).sendKeys("username@makaut.org")
    await driver.findElement(By.css(".flex:nth-child(1) > input")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > input")).sendKeys("Makaut@1234")
    await driver.findElement(By.css(".sign_up_btn")).click()
    await driver.findElement(By.css(".text-3xl:nth-child(1)")).click()
    assert(await driver.findElement(By.css(".text-3xl:nth-child(1)")).getText() == "MAKAUT DASHBOARD")
  })
})
