// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Univer', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Univer', async function() {
    await driver.get("http://localhost:3000/university/dashboard")
    await driver.manage().window().setRect({ width: 1382, height: 754 })
    await driver.findElement(By.css(".uppercase")).click()
    assert(await driver.findElement(By.css(".uppercase")).getText() == "DASHBOARD")
    await driver.findElement(By.id("schools")).click()
    await driver.findElement(By.css(".bg-\\[\\#03071e\\]")).click()
    await driver.findElement(By.id("schoolName")).click()
    await driver.findElement(By.id("schoolName")).sendKeys("SCHOOL OF INFORMATION SCIENCE & TECHNOLOGY")
    await driver.findElement(By.css(".bg-\\[\\#BFC9CA\\]")).click()
    assert(await driver.switchTo().alert().getText() == "School added successfully")
    await driver.findElement(By.css(".text-2xl")).click()
    assert(await driver.findElement(By.css(".text-2xl")).getText() == "SCHOOLS")
    await driver.findElement(By.css(".schools")).click()
    assert(await driver.findElement(By.css(".individual__school > .text-lg")).getText() == "SCHOOL OF INFORMATION SCIENCE & TECHNOLOGY")
    await driver.findElement(By.css(".individual__school > .text-lg")).click()
    await driver.findElement(By.css(".bg-\\[\\#03071e\\]")).click()
    await driver.findElement(By.id("schoolName")).click()
    await driver.findElement(By.id("schoolName")).sendKeys("Department of Information Technology")
    await driver.findElement(By.css(".bg-\\[\\#BFC9CA\\]")).click()
    assert(await driver.switchTo().alert().getText() == "Department added successfully")
    await driver.findElement(By.css(".mx-10")).click()
    assert(await driver.findElement(By.css(".text-xl")).getText() == "DEPARTMENTS")
    await driver.findElement(By.css(".grid")).click()
    assert(await driver.findElement(By.css(".individual__department > .text-sm")).getText() == "Department of Information Technology")
    await driver.findElement(By.css(".individual__department > .text-sm")).click()
    await driver.findElement(By.css(".bg-\\[\\#03071e\\]")).click()
    await driver.findElement(By.id("schoolName")).click()
    await driver.findElement(By.id("schoolName")).sendKeys("B.Tech")
    await driver.findElement(By.css(".bg-\\[\\#BFC9CA\\]")).click()
    assert(await driver.switchTo().alert().getText() == "Program added successfully")
    await driver.findElement(By.css(".individual__department > .text-sm")).click()
    await driver.findElement(By.css(".mx-10")).click()
    assert(await driver.findElement(By.css(".text-xl")).getText() == "PROGRAMS")
    await driver.findElement(By.css(".grid")).click()
    assert(await driver.findElement(By.css(".font-bold:nth-child(1)")).getText() == "B.Tech")
  })
})
