// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('University__signup', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('University__signup', async function() {
    await driver.get("http://localhost:3000/university/signup")
    await driver.manage().window().setRect({ width: 1382, height: 754 })
    await driver.findElement(By.css(".input_box:nth-child(2) > input")).click()
    await driver.findElement(By.css(".input_box:nth-child(2) > input")).sendKeys("New Horizon")
    await driver.findElement(By.css(".input_box:nth-child(3) > input")).click()
    await driver.findElement(By.css(".input_box:nth-child(3) > input")).sendKeys("admissions@horizon.edu")
    await driver.findElement(By.css(".input_box:nth-child(4) > input")).click()
    await driver.findElement(By.css(".input_box:nth-child(4) > input")).sendKeys("8463746246")
    await driver.findElement(By.css(".flex:nth-child(1) > input")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > input")).sendKeys("Newhorizon@1234")
    await driver.findElement(By.css(".sign_up_btn")).click()
    await driver.findElement(By.id("university__login")).click()
    assert(await driver.findElement(By.css(".heading")).getText() == "Login to your account")
  })
})
