name: Check commit message format

on:
  push:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    runs: node-16.x
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install @commitlint/cli @commitlint/config-conventional
      - name: Check commit message format
        run: npx commitlint --from=${{ github.event.before }} --to=${{ github.sha }}
