name: Check Commit Messages
on: push

jobs:
  commit-message-check:
    name: Commit Message Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install @commitlint/cli @commitlint/config-conventional wagoid/commitlint-github-action@v5

      - name: Run Commit Lint
        uses: wagoid/commitlint-github-action@v5
        with:
          config-path: './node_modules/@commitlint/config-conventional/index.js'
