name: Check commit messages

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install commitlint
        run: npm install --save-dev @commitlint/cli @commitlint/config-conventional
      - name: Check commit messages
        run: npx commitlint --from HEAD~1
