name: Check commit message format

on:
  push:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install @commitlint/cli @commitlint/config-conventional
      - name: Check commit message format
        run: npx commitlint --from=${{ github.event.before }} --to=${{ github.sha }}
