name: Commit Message Check
on: [push, pull_request]

jobs:
  commit_message_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Commitlint
      uses: "Wizkeed/commitlint-action@v1"
      with:
        config-path: "./commitlint.config.js"
